name: CI

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up signing key
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo ${{ secrets.KEY_STORE }} | base64 --decode > ./keystore.jks
          fi

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          validate-wrappers: true
          gradle-home-cache-cleanup: true

      - name: Build with Gradle
        run: ./gradlew assembleRelease -PuseExternalSigning
        env:
          RELEASE_KEYSTORE: ../keystore.jks
          RELEASE_KEYSTORE_PASSWORD: '${{ secrets.KEY_STORE_PASSWORD }}'
          RELEASE_KEYSTORE_ALIAS: '${{ secrets.KEY_ALIAS }}'
          RELEASE_KEY_PASSWORD: '${{ secrets.KEY_PASSWORD }}'

      - name: Get release name
        id: release-name
        run: |
          name=`ls app/build/outputs/apk/release/*.apk | awk -F '(/|.apk)' '{print $6}'` && echo "name=${name}" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: EnforceDoze-nightly.apk
          path: app/build/outputs/apk/release/*.apk
          retention-days: 7